"""empty message

Revision ID: 1b730e469486
Revises: 877a80ed0161
Create Date: 2021-01-11 16:13:06.102100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b730e469486'
down_revision = '877a80ed0161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_column('drink', 'drink_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink', sa.Column('drink_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('drink', 'name')
    # ### end Alembic commands ###
